version: '3'
services:
    postgres:
        container_name: todo-postgres
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - postgres-network
volumes:
    postgres_data:
networks:
    postgres-network:
